### PR TITLE
Got authentication up and running

### PR DESCRIPTION
**Pull request by johnathancroom**
- authorize, token!, and authorized? methods working
- creates new connection with oauth2 header if possible

### CODE REVIEW

**Comment by ethnt** [comment]
A few things:
1. Could you rename the `create_connection()` method to `connect!()`. That syntax seems simpler.
2. The OAuth token endpoint is at `http://api.cheddarapp.com/oauth/token`, not at `http://api.cheddarapp.com/v1/oauth/token`.
3. Have you tested this yet? I'll make a test helper, and then I would be eternally grateful if you wrote some tests for this.

**Comment by johnathancroom** [comment]
1. Will do.
2. Since there's a forward slash on the string in authentication.rb:13, it **is** posting to `https://api.cheddarapp.com/oauth/token`. It's written `/oauth/token` and everywhere else is written `lists/1093`.
3. I have tested this and can write some tests for it. They should be rspec in the `/spec` directory? Wouldn't it be better if the directory was renamed to `/tests` or something more relevant. I originally hadn't see the spec directory and that's why I didn't commit any tests.

**Comment by ethnt** [comment]
On [authentication.rb:24](https://github.com/johnathancroom/vermonster/blob/johnny/lib/vermonster.rb#L24), we're creating a Faraday connection to `http://api.cheddarapp.com/v1`, note the `/v1`. I would suggest you use something like this:

``` ruby
Faraday.post 'http://api.cheddarapp.com/oauth/token'
```

I think `/spec` is fine. Most users will know that there are tests in `/spec`.

**Comment by johnathancroom** [comment]
It for **sure** works the way it is now, but if changing it makes it more clear, then I'll change it.

Alright putting tests in `/spec`.

**Comment by ethnt** [comment]
Oh, if it works, don't change it.

**Comment by johnathancroom** [comment]
I've never written tests for an API so these could probably use some refactoring, but it's started.
1. I don't think having to arbitrarily go in and set the client id, client secret, and code is a good idea.
2. The #token! and #authorized? tests cannot be run at the same time because the code expires after one use.

Any help with this would be coolio.

**Comment by ethnt** [comment]
I'm going to pull this into a branch `2-authentication`, we can work on it collaboratively there.

**Pull request closed without merging**
