### PR TITLE
Fixed token! so it displays the token

### PR DESCRIPTION
**Pull request by deanpcmad**
The `token!` call before just displayed true or false. Thinking it was a problem with my app I kept playing around with it but looked through the vermonster code and saw why it was displaying true or false.
This is now fixed so instead of showing true/false, it now shows the token which is what it should show.
Hope this helps :smile:

### CODE REVIEW

**Comment by ethnt** [comment]
Looks good, but we should still call `#authorized?` to ensure that `self.connect!(@client[:token])` succeeds. Otherwise, nice!

**Comment by deanpcmad** [comment]
Sure, maybe check if `authorized?` and then show the token? :)

**Comment by ethnt** [comment]
Sounds good!

**Comment by ethnt** [comment]
I'm going to merge this in, make those changes, and write some tests. Thanks for your contribution!

**Pull request merged**
